on:
  workflow_dispatch:
   inputs:
      file:
        description: 'path of file'
        required: true

jobs:
  test:
   runs-on: ubuntu-latest
   name: to test python
   steps:
      
    - name: install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
        
  
    - name: Run the application
      uses: virtuecloud/Composite-actions/Python_build@test
      with:
        file: ${{ github.event.inputs.file }}
        
