on:
  workflow_dispatch:

jobs:
  test:
   runs-on: ubuntu-latest
   name: to test python
   steps:
      
    - name: checkout
      uses: actions/checkout@v2
      
    - name: install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
        
  
    - name: install the dependency
      uses: virtuecloud/Composite-actions/Build/Python@test
      
    - name: Configure AWS credentials
			uses: peterkimzz/aws-ssm-send-command@1.0.1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          instance-ids: i-0161cb4d1ea84157e
			    comment: Deploy the master branch
			    working-directory: /home/ubuntu
			    command: /bin/sh ./a.sh
       
