on:
  workflow_dispatch:

jobs:
  test:
   runs-on: ubuntu-latest
   name: to test python
   steps:
      
    - name: checkout
      uses: actions/checkout@v2
      
    - name: install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
        
  
    - name: install the dependency
      working-directory: ./python
      run: pip install -r requirements.txt
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./python/ s3://flask-buckett --delete 
      
  deploy:
   runs-on: ubuntu-latest
   name: to deploy python
   needs: test
   
   steps:
      
    - name: checkout
      uses: actions/checkout@v2

      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
    - name: Deploy to ec2
      run: aws ssm send-command --document-name "AWS-RunRemoteScript" --instance-ids "i-0161cb4d1ea84157e" --parameters '{"sourceType":["S3"],"sourceInfo":["{\"path\":\"https://flask-buckett.s3.us-east-1.amazonaws.com/a.sh\"}"],"commandLine":["./a.sh"],"workingDirectory":["/home/ubuntu"]}'
#       run: aws ssm send-command --document-name “AWS-RunRemoteScript” --targets “Key=InstanceIds,Values=[i-0161cb4d1ea84157e]” --parameters ‘{“sourceType”:["S3"],“sourceInfo”:[“{\“path\“:\“s3://flask-buckett\“}”],“commandLine”:[“./a.sh”]}’
