on:
  workflow_dispatch:

jobs:
  test:
   runs-on: ubuntu-latest
   name: to test python
   steps:
      
    - name: checkout
      uses: actions/checkout@v2
      
    - name: install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
        
  
    - name: install the dependency
      uses: virtuecloud/Composite-actions/Build/Python@test
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

    - name: AWS SSM Send-Command
      run: aws ssm send-command --document-name "AWS-RunRemoteScript" --instance-ids "i-0161cb4d1ea84157e" --parameters '{"sourceType":["GitHub"],"sourceInfo":["{\"owner\":\"Jainsi1\", \"repository\":\"flaskapp\", \"path\":\"python\"}"],"commandLine":["python index.py"]}'
      shell: bash        
