on:
  workflow_dispatch:

jobs:
  test:
   runs-on: ubuntu-latest
   name: to test python
   steps:
      
    - name: checkout
      uses: actions/checkout@v2
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
    - name: Deploy static site to S3 bucket
      uses: virtuecloud/Compostite-actions/Deploy/s3_sync@main
      with:
          BUCKET_NAME: renn      # name of bucket
          PATH: ./python         # path of folder/file to be uploaded
      
  deploy:
   runs-on: ubuntu-latest
   name: to deploy python
   needs: test
   
   steps:
      
    - name: checkout
      uses: actions/checkout@v2

      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
    - name: Deploy to ec2
      uses: irtuecloud/Compostite-actions/Deploy/EC2_Deploy@main
      with:
          INSTANCE_ID: 0bc9ff54f414b5e1c
          BUCKET_NAME: renn
          BUCKET_REGION: us-east-1
          WORKDIR: /home/ubuntu
          FILE: a.sh
