on:
  workflow_dispatch:
    inputs:
      bucketname:
        description: name of bucket
        required: true
      bucketregion:
        description: region of bucket
        required: true
      path:
        description: path of folder/file to be uploaded
        required: true
      instanceid:
        description: Instance on which you want to deploy
        required: true
      workdir:
        description: directory where your bash file should run
        required: false
      file:
        description: name of bash file
        required: true
jobs:
  test:
   runs-on: ubuntu-latest
   name: to test python
   steps:
      
    - name: checkout
      uses: actions/checkout@v2
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
    - name: Deploy static site to S3 bucket
      uses: virtuecloud/Compostite-actions/Deploy/s3_sync@main
      with:
          BUCKET_NAME: ${{ github.event.inputs.bucketname }}     
          PATH: ${{ github.event.inputs.path }}        
      
  deploy:
   runs-on: ubuntu-latest
   name: to deploy python
   needs: test
   
   steps:
      
    - name: checkout
      uses: actions/checkout@v2

      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
    - name: Deploy to ec2
      uses: virtuecloud/Compostite-actions/Deploy/EC2_Deploy@main
      with:
          INSTANCE_ID: ${{ github.event.inputs.instanceid }}
          BUCKET_NAME: ${{ github.event.inputs.bucketname }}
          BUCKET_REGION: ${{ github.event.inputs.bucketregion }}
          WORKDIR: ${{ github.event.inputs.workdir }}
          FILE: ${{ github.event.inputs.file }}
